/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

/**
 *
 * @author Barbara
 */
public class ClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MascotaView
     */
    public ClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Cliente N°");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 90, 120, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 150, 70, 20);

        jLabel5.setText("DNI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 20);

        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(60, 150, 90, 20);

        jLabel6.setText("Apelldio");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 150, 70, 20);

        jTextField4.setText("jTextField1");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 150, 140, 20);

        jTextField5.setText("jTextField1");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(450, 150, 140, 20);

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(310, 90, 110, 30);

        jLabel9.setText("Direcion");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 190, 120, 20);

        jTextField7.setText("jTextField1");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(150, 250, 410, 20);

        jLabel10.setText("Contacto Alternativo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 250, 100, 20);

        jRadioButton1.setText("Activo");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(150, 290, 93, 23);

        jRadioButton2.setText("Inactivo");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(360, 290, 65, 23);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel13.setText("Datos Basicos");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 0, 171, 20);

        jButton1.setText("Salir");
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 40, 80, 23);

        jButton2.setText("Guardar");
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 40, 71, 23);

        jButton3.setText("Actualizar");
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 40, 80, 23);

        jButton4.setText("Buscar Por");
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 480, 110, 23);

        jButton5.setText("Borrar");
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 40, 80, 23);

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel15.setText("Listado de Clientes");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(100, 480, 200, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(290, 350, 280, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 400, 570, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 22, 130, 10);

        jTextField9.setText("jTextField1");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(150, 190, 300, 20);

        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 220, 70, 20);

        jTextField10.setText("jTextField1");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(150, 220, 410, 20);

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel16.setText("Mascotas a su cargo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 350, 200, 20);

        jButton6.setText("Buscar");
        getContentPane().add(jButton6);
        jButton6.setBounds(70, 40, 70, 23);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 72, 530, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 320, 50, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 320, 570, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(10, 470, 590, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
