/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

/**
 *
 * @author Barbara
 */
public class ClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MascotaView
     */
    public ClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Cliente N°");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 110, 120, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 190, 70, 20);

        jLabel5.setText("DNI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 190, 70, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 190, 90, 20);

        jLabel6.setText("Apellido");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 190, 70, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(260, 190, 140, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(470, 190, 140, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(330, 110, 180, 30);

        jLabel9.setText("Direcion");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 120, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 300, 410, 20);

        jLabel10.setText("Contacto Alternativo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 300, 100, 20);

        jRadioButton1.setText("Activo");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(200, 340, 93, 23);

        jRadioButton2.setText("Inactivo");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(390, 340, 65, 23);

        jButton1.setText("Salir");
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 60, 80, 23);

        jButton2.setText("Guardar");
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 60, 71, 23);

        jButton3.setText("Actualizar");
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 60, 80, 23);

        jButton5.setText("Borrar");
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 60, 80, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(310, 400, 280, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 450, 570, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 630, 10);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(200, 240, 410, 20);

        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 270, 70, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(200, 270, 410, 20);

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel16.setText("Mascotas a su cargo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(80, 400, 200, 20);

        jButton6.setText("Buscar");
        getContentPane().add(jButton6);
        jButton6.setBounds(70, 60, 70, 23);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 100, 600, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 320, 0, 2);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(40, 380, 570, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(10, 470, 590, 2);

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel14.setText(" CLIENTES: Datos Basicos");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 20, 270, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
