/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS2;

import CONTROLADOR.ClienteData;
import CONTROLADOR.Conexion;
import CONTROLADOR.MascotaData;
import CONTROLADOR.TratamientoData;
import CONTROLADOR.VisitaData;
import VISTAS.MenuPrincipal_VETE;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Barbara
 */
public class Menu_PRINCIPAL_VETE2 extends javax.swing.JFrame {
    
    Conexion conexion = null;
    private ClienteData cd;
    private MascotaData md;
    private TratamientoData td;
    private VisitaData vd;
    
    

    /**
     * Creates new form Menu_VETE2
     */
    public Menu_PRINCIPAL_VETE2() {

        try {
            this.conexion = new Conexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal_VETE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cd = new ClienteData(conexion);
        this.md = new MascotaData(conexion);
        this.td = new TratamientoData(conexion);
        this.vd = new VisitaData(conexion);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    private boolean revisarCamposVaciosClientes() {
//        if (jTextDNI.getText().isEmpty()) {
//            jTextDNI.requestFocus();
//            JOptionPane.showMessageDialog(null, "DNI no puede estar vacio");
//            return false;
//        } else if (jTextApellido.getText().isEmpty()) {
//            jTextApellido.requestFocus();
//            JOptionPane.showMessageDialog(null, "Apellido no puede estar vacio");
//            return false;
//        } else if (jTextNombre.getText().isEmpty()) {
//            jTextNombre.requestFocus();
//            JOptionPane.showMessageDialog(null, "Nombre no puede estar vacio");
//            return false;
//        } else if (jTextDireccion.getText().isEmpty()) {
//            jTextDireccion.requestFocus();
//            JOptionPane.showMessageDialog(null, "Direccion no puede estar vacia");
//            return false;
//        } else if (jTextTelefono.getText().isEmpty()) {
//            jTextTelefono.requestFocus();
//            JOptionPane.showMessageDialog(null, "Telefono no puede estar vacio");
//            return false;
//        } else if (jTextContactoA.getText().isEmpty()) {
//            jTextContactoA.requestFocus();
//            JOptionPane.showMessageDialog(null, "Contacto alternativo no puede estar vacio");
//            return false;
//        } else {
//            return true;
//        }
//
//    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuPrincipal = new javax.swing.JMenuBar();
        jM_CLIENTES = new javax.swing.JMenu();
        jM_FICHA_CLIENTE = new javax.swing.JMenuItem();
        jM_MASCOTAS = new javax.swing.JMenu();
        jM_FICHA_MASCOTA = new javax.swing.JMenuItem();
        jM_TRATAMIENTOS = new javax.swing.JMenu();
        jM_FICHA_TRATAMIENTOS = new javax.swing.JMenuItem();
        jM_VISITAS = new javax.swing.JMenu();
        jM_FICHA_VISITAS = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jMConsultasCLIENTES = new javax.swing.JMenuItem();
        jMConsultasMASCOTAS = new javax.swing.JMenuItem();
        jMConsultasTRATAMIENTOS = new javax.swing.JMenuItem();
        jMConsultasVISITAS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\PROYECTO FINAL\\IMAGENES\\fondo _menu.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jM_CLIENTES.setText("Clientes");

        jM_FICHA_CLIENTE.setText("Ficha CLIENTE");
        jM_FICHA_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_FICHA_CLIENTEActionPerformed(evt);
            }
        });
        jM_CLIENTES.add(jM_FICHA_CLIENTE);

        jMenuPrincipal.add(jM_CLIENTES);

        jM_MASCOTAS.setText("Mascotas");

        jM_FICHA_MASCOTA.setText("Ficha MASCOTA");
        jM_FICHA_MASCOTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_FICHA_MASCOTAActionPerformed(evt);
            }
        });
        jM_MASCOTAS.add(jM_FICHA_MASCOTA);

        jMenuPrincipal.add(jM_MASCOTAS);

        jM_TRATAMIENTOS.setText("Tratamientos");

        jM_FICHA_TRATAMIENTOS.setText("Ficha TRATAMIENTO");
        jM_TRATAMIENTOS.add(jM_FICHA_TRATAMIENTOS);

        jMenuPrincipal.add(jM_TRATAMIENTOS);

        jM_VISITAS.setText("Visitas");

        jM_FICHA_VISITAS.setText("Ficha VISITAS");
        jM_VISITAS.add(jM_FICHA_VISITAS);

        jMenuPrincipal.add(jM_VISITAS);

        jConsultas.setText("Consultas");

        jMConsultasCLIENTES.setText("Consultas de Clientes");
        jConsultas.add(jMConsultasCLIENTES);

        jMConsultasMASCOTAS.setText("Consulta de Mascotas");
        jMConsultasMASCOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultasMASCOTASActionPerformed(evt);
            }
        });
        jConsultas.add(jMConsultasMASCOTAS);

        jMConsultasTRATAMIENTOS.setText("Consulta de Tratamientos");
        jConsultas.add(jMConsultasTRATAMIENTOS);

        jMConsultasVISITAS.setText("Consulta de Visitas");
        jConsultas.add(jMConsultasVISITAS);

        jMenuPrincipal.add(jConsultas);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_FICHA_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_FICHA_CLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_FICHA_CLIENTEActionPerformed

    private void jMConsultasMASCOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultasMASCOTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMConsultasMASCOTASActionPerformed

    private void jM_FICHA_MASCOTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_FICHA_MASCOTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_FICHA_MASCOTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_PRINCIPAL_VETE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_PRINCIPAL_VETE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_PRINCIPAL_VETE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_PRINCIPAL_VETE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_PRINCIPAL_VETE2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMConsultasCLIENTES;
    private javax.swing.JMenuItem jMConsultasMASCOTAS;
    private javax.swing.JMenuItem jMConsultasTRATAMIENTOS;
    private javax.swing.JMenuItem jMConsultasVISITAS;
    private javax.swing.JMenu jM_CLIENTES;
    private javax.swing.JMenuItem jM_FICHA_CLIENTE;
    private javax.swing.JMenuItem jM_FICHA_MASCOTA;
    private javax.swing.JMenuItem jM_FICHA_TRATAMIENTOS;
    private javax.swing.JMenuItem jM_FICHA_VISITAS;
    private javax.swing.JMenu jM_MASCOTAS;
    private javax.swing.JMenu jM_TRATAMIENTOS;
    private javax.swing.JMenu jM_VISITAS;
    private javax.swing.JMenuBar jMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
